### ISSUE TITLE
Barra de navegación oculta parte de listado

### ISSUE THREAD

**Issue by edgar-melara-uniandes** [clts-uniandes/DesarrolloMovil#118]
La barra de navegación inferior oculta la ultima parte del listado de un album

<img width="307" alt="image" src="https://user-images.githubusercontent.com/98713869/202960435-0cecb7b7-8935-4d47-8e74-d34b8a2e8011.png">

**Comment by clts-uniandes** [comment]
Bug resuelto en ultima versión del app
